<a href="https://colab.research.google.com/github/bartoszgajda55/Tensorflow2DeepLearning/blob/master/TF2.0%20RNN%20Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Things to memorize:
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [4]:
# Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [7]:
# Make an RNN
M = 5
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [10]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

[[-1.7341323  0.9899142]]


In [12]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 5)                 45        
_________________________________________________________________
dense (Dense)                (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.layers[1].get_weights()

[array([[-0.26089716, -0.7260444 , -0.3201638 ,  0.13152248, -0.09414959],
        [ 0.24282879,  0.17981893,  0.06533104,  0.63076144, -0.3248167 ],
        [-0.09168488,  0.12410563, -0.7425716 , -0.32368958, -0.69200015]],
       dtype=float32),
 array([[-0.32713914, -0.24605912, -0.37320453, -0.35365438,  0.753712  ],
        [-0.5919359 , -0.6078441 , -0.10199948,  0.41629612, -0.31053331],
        [-0.66437566,  0.69957817,  0.14926714,  0.19039457,  0.10326925],
        [ 0.20611392, -0.1582463 ,  0.49415043,  0.6058639 ,  0.5667623 ],
        [ 0.24230956,  0.23564543, -0.7641003 ,  0.54617304,  0.06002626]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [16]:
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)
